model_id: segment_anything_3
display_name: "Segment Anything 3"

params:
  bpe_path: "bpe_simple_vocab_16e6.txt.gz"
  model_path: "sam3.pt"
  device: "cuda:0"
  conf_threshold: 0.50
  show_boxes: true
  show_masks: true
  epsilon_factor: 0.001

widgets:
  - name: edit_text
    value: null
  - name: button_send
    value: null
  - name: add_pos_rect
    value: null
  - name: add_neg_rect
    value: null
  - name: button_run_rect
    value: null
  - name: button_clear
    value: null
  - name: button_finish_object
    value: null
  - name: input_conf
    value: null
  - name: edit_conf
    value: 0.25
  - name: mask_fineness_slider
    value: 10
  - name: mask_fineness_value_label
    value: null
  - name: toggle_preserve_existing_annotations
    value: false
